# Generated by Django 4.0 on 2022-04-04 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='course',
        ),
        migrations.AddField(
            model_name='job',
            name='institution',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='core.institution'),
            preserve_default=False,
        ),
    ]
