# Generated by Django 4.0 on 2022-04-04 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_job_course_job_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='institution',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
