# Generated by Django 4.0 on 2022-04-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_semester_institution_delete_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='name',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
