# Generated by Django 4.0 on 2022-04-04 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tag_job_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='assigned_to',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='core.scheduleuser'),
        ),
        migrations.AlterField(
            model_name='job',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='core.Tag'),
        ),
    ]
