# Generated by Django 4.0 on 2022-04-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_job_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('U', 'Unclaimed'), ('C', 'Claimed'), ('P', 'Pending Edits/Approval'), ('D', 'Done')], max_length=1),
        ),
    ]
