# Generated by Django 4.0.3 on 2022-04-08 04:39

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default=0, max_length=128, region=None),
            preserve_default=False,
        ),
    ]
