# Generated by Django 4.0.3 on 2022-04-08 04:47

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_scheduleuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
