# Generated by Django 4.0.3 on 2022-04-14 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_job_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
