# Generated by Django 4.0.3 on 2022-04-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_job_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleuser',
            name='new_job_txt_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
