# Generated by Django 4.0.3 on 2022-04-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_scheduleuser_new_job_txt_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfile',
            name='file_type',
            field=models.CharField(choices=[('S', 'Source Material'), ('C', 'Completed Material'), ('O', 'Other Material')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='jobfile',
            name='file',
            field=models.FileField(upload_to='uploads/%Y/%a/%d/%h:%m:%s/'),
        ),
    ]
