# Generated by Django 4.0.3 on 2022-04-14 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_jobfile_file_type_alter_jobfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='institution',
        ),
    ]
