# Generated by Django 4.0.3 on 2022-04-14 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_job_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
