# Generated by Django 4.0.3 on 2022-04-20 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_job_submitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='due_date',
            field=models.DateTimeField(),
        ),
    ]
