# Generated by Django 4.0.3 on 2022-04-20 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_institution_id_alter_jobfile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recieving_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transcriber_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
