# Generated by Django 4.0.3 on 2022-04-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_job_recipient_alter_job_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleuser',
            name='job_completed_txt_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scheduleuser',
            name='job_pending_edits_txt_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
