# Generated by Django 4.0.3 on 2022-04-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_scheduleuser_job_completed_txt_notifications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='scheduleuser',
            name='new_job_notifications',
            field=models.ManyToManyField(blank=True, default=[], null=True, to='core.notificationtype'),
        ),
    ]
