# Generated by Django 4.0.3 on 2022-04-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_scheduleuser_new_job_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleuser',
            name='job_completed_notifications',
            field=models.ManyToManyField(blank=True, default=[], related_name='completed_users', to='core.notificationtype'),
        ),
        migrations.AddField(
            model_name='scheduleuser',
            name='job_pending_edits_notifications',
            field=models.ManyToManyField(blank=True, default=[], related_name='review_users', to='core.notificationtype'),
        ),
        migrations.AlterField(
            model_name='scheduleuser',
            name='new_job_notifications',
            field=models.ManyToManyField(blank=True, default=[], related_name='new_job_users', to='core.notificationtype'),
        ),
    ]
