# Generated by Django 4.0.3 on 2022-04-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_scheduleuser_job_completed_notifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtype',
            name='name',
            field=models.CharField(editable=False, max_length=1),
        ),
    ]
