# Generated by Django 4.0.3 on 2022-06-07 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_scheduleuser_job_completed_txt_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
